### ISSUE TITLE
Compliments and collaboration

### ISSUE THREAD

**Issue by sirhashalot** [sayan011/Immunefi-bug-bounty-writeups-list#2]
Nice list. There is a lot of similarity with a list I have maintained https://github.com/sirhashalot/SCV-List

I suggest we combine efforts to collaborate on one list. You can propose the next step if this is an interesting idea, perhaps creating a new org that we are admins of for a combined repo. If this is not an interesting idea, you can close this issue.

**Comment by sayan011** [comment]
Cool idea, let's do it !
I'll DM you on twitter to discuss further :)
btw your list is awesome & much more comprehensive than mine.
